AWSTemplateFormatVersion: 2010-09-09
Description: >-
  notes-api
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  # This is a Lambda function config associated with the source code: get-all-items.js
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items 
        from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the NotesTable
      - DynamoDBCrudPolicy:
          TableName: !Ref NotesTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          NOTES_TABLE_NAME: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-by-id.js
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item 
        by id from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the NotesTable
      - DynamoDBCrudPolicy:
          TableName: !Ref NotesTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          NOTES_TABLE_NAME: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes/{noteId}
            Method: GET
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: put-item.js
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP post method to add one item 
        to a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the NotesTable
      - DynamoDBCrudPolicy:
          TableName: !Ref NotesTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          NOTES_TABLE_NAME: !Ref NotesTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /notes
            Method: POST

  updateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/update-note.updateNoteHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        UpdateNote:
          Type: Api
          Properties:
            Path: /notes/{noteId}
            Method: put

  deleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handlers/delete-note.deleteNoteHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          NOTES_TABLE_NAME: !Ref NotesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NotesTable
      Events:
        DeleteNote:
          Type: Api
          Properties:
            Path: /notes/{noteId}
            Method: delete

  # Simple syntax to create a DynamoDB table with a single attribute primary key, more in
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
